
const descripciones = {
    agua : "Se estira el índice, y se señala hacia adelante, simulando el flujo del agua.",
    abrir : "Se colocan las manos tocándose por la punta de los dedos, y se mueven al mismo tiempo a los lados, hasta separarse",
    abajo : "Se estira el índice, y se señala hacia abajo.",
    acompanado : "Se coloca una letra c sobre el otro brazo,tocándolo con la parte lateral del dedo meñique, y se realiza un movimiento de medio círculo hacia la muñeca.",
    aqui : "Con la mano cerrada y el índice estirado se señala el piso.",
    balon : "Con las manos en posición cóncava, una frente a la otra, se simula sostener un balón.",
    bondad : "Se coloca una letra b sobre el corazón, y se hace vibrar en su lugar, posteriormente se coloca una letra d sobre la otra mano, quedando dorso con dorso.",
    bonito : "Se coloca la mano abierta frente a la cara, y se mueve en círculo. Se termina con la mano cerrada en punta, señalando hacia usted.",
    bueno : "Se hace una letra b sobre el corazón y se mueve hacia el frente.",
    cerrar : "(LLAVE -cerrar con)  Se coloca la mano cerrada sobre la palma de la otra mano, y se realiza un movimiento rotatorio de muñeca hacia los lados.",
    comida : "Con una mano se forma un capullo y con él se señala la boca. Se hace un movimiento al frente y de regreso, luego se hace una b a la altura de la frente por la parte lateral del dedo índice, y se mueve hacia abajo en línea recta.",
    cual : "Se coloca la mano con el índice levantado y se mueve ligeramente de un lado a otro, como preguntando entre opciones.",
    cuidado : "Se coloca una mano abierta frente al pecho y con la otra se hace un movimiento semicircular hacia adelante, como advirtiendo o pidiendo atención.",
    diferente : "Se encuentran los índices estirados uno frente al otro y se mueven en direcciones opuestas formando una X que se separa.( “diferente/igual”)",
    dirigir : "Se coloca una letra d sobre el otro brazo, tocándolo con la parte lateral del dedo meñique, y se realiza un movimiento de medio círculo hacia la muñeca.",
    duda : "Se forma una letra d con la mano y se coloca sobre la frente, moviéndola ligeramente hacia abajo en señal de incertidumbre.",
    dulce : "Se hace una u sobre los labios, y luego se mueve hacia abajo hasta cerrar la mano.",
    enojado : "Con una mano cerrada se golpea ligeramente el pecho, mostrando molestia.",
    entregar : "Se coloca una letra e sobre la otra mano y se mueve hacia adelante simulando dar algo.",
    escalera : "Se colocan ambas manos con los dedos extendidos y se mueven alternadas hacia arriba o hacia abajo, imitando el subir o bajar escalones.",
    espejo : "Se colocan ambas manos abiertas frente a la cara, con palmas hacia uno mismo, simulando el marco de un espejo.",
    favor : "Se hace una letra f y se mueve hacia adelante desde el pecho, como pidiendo algo con amabilidad.",
    fin : "Se hace una letra f y luego una letra n, siguiendo un movimiento descendente que marca término.",
    foco : "Se coloca la mano en forma de “C” sobre la cabeza, simulando el foco, y se abre la mano súbitamente para representar que se enciende.",
    frio : "Se colocan ambas manos cerradas frente al cuerpo, con antebrazos levantados, y se agitan ligeramente como si uno estuviera tiritando.",
    fuego : "Se colocan ambas manos abiertas con dedos separados frente al cuerpo y se mueven hacia arriba de forma ondulante, imitando llamas.",
    golpear : "Se hace un puño con una mano y con la otra mano abierta se simula recibir un golpe, tocando el dorso del puño.",
    guardar : "Se tiene una mano en forma de “cajita” y con la otra mano se mete algo adentro, cerrando al final.",
    hacer : "Se colocan ambas manos en forma de puño y se realizan movimientos circulares alternados, como si se mezclara o trabajara algo.",
    hambre : "Se colocan las manos abiertas a la altura del estómago, y lo tocan con la punta de los dedos; luego se mueven al frente, y al mismo tiempo se cierran.",
    hogar : "Se juntan las puntas de los dedos de ambas manos formando un techo y se baja hacia los lados simulando una casita.",
    horno : "Se forma una “caja” con ambas manos y se mete la otra mano como si se introdujera una charola, deslizando al centro.",
    iglesia : "Se hace una letra “i” y se mueve hacia abajo tocando la palma de la otra mano, que está abierta hacia arriba; luego se abre la mano en forma de techo.",
    invitar : "Se colocan ambas manos abiertas hacia uno mismo y se mueven hacia adelante como invitando a alguien a acercarse.",
    jardin : "Se colocan las manos abiertas a la altura de la cintura y se mueven hacia los lados en pequeños arcos, como mostrando plantas a los costados.",
    jerga : "Se sostiene una mano abierta hacia abajo como si fuera un trapo, y con la otra mano se hace un movimiento de frotar hacia adelante y atrás.",
    jugar : "Se hacen dos letras “y” (meñique y pulgar extendidos) y se mueven ambas de lado a lado de manera alternada.",
    lampara : "Se coloca una mano en forma de “C” sobre la cabeza como si fuera un foco colgante, y se abre ligeramente la mano superior como “encendiendo”.",
    libre : "Se colocan ambas manos en forma de “L”, cruzadas frente al pecho, y luego se separan haciéndose hacia afuera en un movimiento de soltura.",
    licuadora : "Se coloca una mano como vaso (mano en “C”) y con la otra se hace un movimiento circular sobre la “tapa”, como si se encendiera para licuar.",
    llave : "Con una mano se forma la cerradura (puño con el pulgar arriba) y con la otra se simula la llave haciendo un giro con el dedo índice estirado.",
    luna : "Se forma una “C” con la mano y se eleva hacia un lado del rostro, inclinándola un poco hacia adelante como si se mostrara la forma de la luna.",
    mama : "MAMÁ se hace con la letra m (ideograma) golpeando varias veces los labios.",
    manejar : "Se colocan ambas manos como si se sujetara un volante pequeño y se realizan leves giros hacia los lados.",
    momentito : "Se coloca el índice levantado frente al cuerpo y se hace un pequeño movimiento hacia abajo, marcando que es rápido o breve.",
    mujer : "Se desliza la mano abierta desde la mejilla hacia abajo, siguiendo la línea del rostro, y se termina con la mano abierta hacia el frente.",
    nadar : "Se mueven ambas manos alternadas al frente imitando el movimiento de nado de pecho.",
    nina : "Se hace la seña de “mujer” (mano desde la mejilla hacia abajo) y luego se señala hacia abajo o hacia un lado para indicar “chica/pequeña”.",
    nino : "Se hace la seña de “hombre” (mano desde la frente hacia abajo) y luego se apunta hacia abajo o a un costado para indicar “pequeño”.",
    noesta : "Se coloca una mano abierta frente al cuerpo y se mueve hacia los lados en negación, mientras la otra mano hace un gesto de ausencia (mano vacía que se retira).",
    oir : "Se lleva el índice hacia la oreja y se hace un pequeño movimiento tocando o acercándolo, indicando que se escucha.",
    ojala : "Se juntan ambas manos como en oración y se suben ligeramente hacia el pecho, mostrando deseo o esperanza.",
    otravez : "Se hace un movimiento semicircular llevando la mano hacia la palma de la otra, como si se repitiera el gesto nuevamente.",
    otro : "Se forma una letra “o” con la mano y se mueve hacia un lado, como indicando “uno diferente”.",
    papa : "Se hace la letra “p” y se toca ligeramente la frente varias veces.",
    pasos : "Se colocan ambas manos con los dedos extendidos hacia abajo y se alternan pequeños movimientos hacia adelante, imitando caminar.",
    paz : "Se deletrea la palabra la. Luego se hace la letra p con ambas manos, y se dibuja una z en el aire hasta terminar con la letra a.",
    pena : "Se coloca la mano abierta sobre la mejilla y se baja ligeramente la cabeza, como mostrando vergüenza o timidez.",
    persona : "Se colocan ambas manos abiertas frente al cuerpo y se bajan hacia abajo marcando una silueta, como indicando a un individuo.",
    querer : "Se colocan ambas manos en forma de garras sobre el pecho y se jalan ligeramente hacia uno mismo, como “sentir deseo”.",
    quinto : "Se muestra la mano con cinco dedos, luego se señala el meñique para indicar “el quinto”.",
    radio : "Se hace la forma de un aparato rectangular con ambas manos y luego se lleva una mano hacia la oreja, como escuchando algo.",
    rebanar : "Se coloca una mano como sosteniendo un alimento y con la otra se hace un movimiento repetido de corte hacia abajo.",
    regresar : "Se hace una curva con el dedo índice hacia atrás, como indicando volver al punto de origen.",
    resumen : "Se junta una mano abierta sobre la otra como si se agrupara información, y luego se desliza hacia adelante en movimiento corto, indicando “concentrar” o “sintetizar”.",
    senor : "Se hace la letra s a la altura de la frente y se baja hacia el pecho en línea recta, similar a “hombre” pero usando la inicial.",
    sentar : "Se coloca una mano horizontal representando un asiento, y con la otra mano se hace un movimiento corto descendente como si alguien se sentara sobre ella.",
    soltar : "Se hace un puño con la mano y luego se abre rápidamente hacia abajo, como dejando caer algo.",
    sonar : "Se toca ligeramente la sien con el índice y se mueve la mano hacia adelante dibujando un pequeño arco, como “imaginar algo”.",
    tener : "Se coloca la mano en forma curva y se apoya sobre el pecho, marcando posesión.",
    tienda : "Se forman ambas manos en forma de techo (como casa) y luego se hacen pequeños movimientos hacia adelante como si se atendiera un negocio.",
    tomar : "Se hace la forma de agarrar un vaso con la mano y se lleva hacia la boca simulando beber.",
    transformar : "Se colocan ambas manos abiertas frente a frente y se giran sobre sí mismas intercambiando posición, como cambiando algo a otra forma.",
    unido : "Se juntan las puntas de los dedos de ambas manos formando una especie de círculo cerrado, mostrando conexión firme.",
    untar : "Se coloca una mano como si fuera una superficie plana y con la otra se hace un movimiento hacia adelante y atrás, como extendiendo mantequilla o crema.",
    urgente : "Se realizan dos golpes rápidos con el índice sobre la palma abierta de la otra mano, indicando premura.",
    usar : "Se coloca un objeto imaginario sobre la mano y se hace un movimiento de manipularlo, como indicando que se utiliza.",
    valioso : "Se hace una “v” y se lleva al pecho, luego se mueve hacia afuera con un gesto de cuidado, como mostrando que algo es importante.",
    ver : "Se apuntan los ojos con el índice y el medio, y luego se mueve la mano hacia adelante, como proyectando la mirada.",
    viejo : "Se coloca una mano en forma de garra sobre la mejilla y se baja lentamente, como representando arrugas o edad avanzada.",
    volar : "Se juntan los pulgares y se abren las manos como alas, moviéndolas de arriba hacia abajo suavemente.",
    whisky : "Se forma un vaso con la mano y se inclina ligeramente hacia la boca, haciendo un pequeño gesto de sabor fuerte.",
    xalapa : "Se hace la letra X y se mueve ligeramente hacia abajo y al frente, representando la inicial de la ciudad.",
    yucatan : "Se hace la letra Y y se apunta hacia abajo, indicando ubicación geográfica del estado.",
    zanahoria : "Se forma un cilindro con una mano (como sostener una zanahoria) y con la otra mano se hace un movimiento de pelar de arriba hacia abajo.",
    zapato : "Se coloca una mano en forma de zapato (mano curva) y con la otra se dan pequeños golpecitos sobre el “talón”.",
    zapote : "Se forma un círculo grande con ambas manos y se toca ligeramente con la otra mano como señalando la fruta redonda.",
};

export default descripciones;