
export default {
  "abajo.png": require("../assets/SIGN IMAGES/abajo.png"),
  "acompanado.png": require("../assets/SIGN IMAGES/acompanado.png"),
  "agua.png": require("../assets/SIGN IMAGES/agua.png"),
  "aqui.png": require("../assets/SIGN IMAGES/aqui.png"),
  "balon.png": require("../assets/SIGN IMAGES/balon.png"),
  "bondad.png": require("../assets/SIGN IMAGES/bondad.png"),
  "bonito.png": require("../assets/SIGN IMAGES/bonito.png"),
  "bueno.png": require("../assets/SIGN IMAGES/bueno.png"),
  "cerrar.png": require("../assets/SIGN IMAGES/cerrar.png"),
  "comida.png": require("../assets/SIGN IMAGES/comida.png"),
  "cual.png": require("../assets/SIGN IMAGES/cual.png"),
  "cuidado.png": require("../assets/SIGN IMAGES/cuidado.png"),
  "diferente.png": require("../assets/SIGN IMAGES/diferente.png"),
  "dirigir.png": require("../assets/SIGN IMAGES/dirigir.png"),
  "duda.png": require("../assets/SIGN IMAGES/duda.png"),
  "dulce.png": require("../assets/SIGN IMAGES/dulce.png"),
  "enojado.png": require("../assets/SIGN IMAGES/enojado.png"),
  "entregar.png": require("../assets/SIGN IMAGES/entregar.png"),
  "escalera.png": require("../assets/SIGN IMAGES/escalera.png"),
  "espejo.png": require("../assets/SIGN IMAGES/espejo.png"),
  "favor.png": require("../assets/SIGN IMAGES/favor.png"),
  "fin.png": require("../assets/SIGN IMAGES/fin.png"),
  "foco.png": require("../assets/SIGN IMAGES/foco.png"),
  "frio.png": require("../assets/SIGN IMAGES/frio.png"),
  "fuego.png": require("../assets/SIGN IMAGES/fuego.png"),
};