// Mapeo de videos de señas
export default {
  "abajo.mp4": require("../assets/SING_VIDEOS/abajo.mp4"),
  "aqui.mp4": require("../assets/SING_VIDEOS/aqui.mp4"),
  "balon.mp4": require("../assets/SING_VIDEOS/balon.mp4"),
  "bondad.mp4": require("../assets/SING_VIDEOS/bondad.mp4"),
  "bonito.mp4": require("../assets/SING_VIDEOS/bonito.mp4"),
  "bueno.mp4": require("../assets/SING_VIDEOS/bueno.mp4"),
  "cerrar.mp4": require("../assets/SING_VIDEOS/cerrar.mp4"),
  "comida.mp4": require("../assets/SING_VIDEOS/comida.mp4"),
  "cuidado.mp4": require("../assets/SING_VIDEOS/cuidado.mp4"),
  "diferente.mp4": require("../assets/SING_VIDEOS/diferente.mp4"),
  "duda.mp4": require("../assets/SING_VIDEOS/duda.mp4"),
  "dulce.mp4": require("../assets/SING_VIDEOS/dulce.mp4"),
  "enojado.mp4": require("../assets/SING_VIDEOS/enojado.mp4"),
  "entregar.mp4": require("../assets/SING_VIDEOS/entregar.mp4"),
  "espejo.mp4": require("../assets/SING_VIDEOS/espejo.mp4"),
//   "acompañado.mp4": require("../assets/SING_VIDEOS/acompañado.mp4"),
//   "cual.mp4": require("../assets/SING_VIDEOS/cual.mp4"),
//   "dirigir.mp4": require("../assets/SING_VIDEOS/dirigir.mp4"),
  "escalera.mp4": require("../assets/SING_VIDEOS/escalera.mp4"),
  "favor.mp4": require("../assets/SING_VIDEOS/favor.mp4"),
//   "fin.mp4": require("../assets/SING_VIDEOS/fin.mp4"),
  "foco.mp4": require("../assets/SING_VIDEOS/foco.mp4"),
  "frio.mp4": require("../assets/SING_VIDEOS/frio.mp4"),
  "fuego.mp4": require("../assets/SING_VIDEOS/fuego.mp4"),
  "golpear.mp4": require("../assets/SING_VIDEOS/golpear.mp4"),
  "guardar.mp4": require("../assets/SING_VIDEOS/guardar.mp4"),
  "hacer.mp4": require("../assets/SING_VIDEOS/hacer.mp4"),
  "hambre.mp4": require("../assets/SING_VIDEOS/hambre.mp4"),
  "hogar.mp4": require("../assets/SING_VIDEOS/hogar.mp4"),
  "horno.mp4": require("../assets/SING_VIDEOS/horno.mp4"),
  "iglesia.mp4": require("../assets/SING_VIDEOS/iglesia.mp4"),
  "invitar.mp4": require("../assets/SING_VIDEOS/invitar.mp4"),
//   "jardin.mp4": require("../assets/SING_VIDEOS/jardin.mp4"),
//   "jerga.mp4": require("../assets/SING_VIDEOS/jerga.mp4"),
  "jugar.mp4": require("../assets/SING_VIDEOS/jugar.mp4"),
  "lampara.mp4": require("../assets/SING_VIDEOS/lampara.mp4"),
  "libre.mp4": require("../assets/SING_VIDEOS/libre.mp4"),
  "licuadora.mp4": require("../assets/SING_VIDEOS/licuadora.mp4"),
  "llave.mp4": require("../assets/SING_VIDEOS/llave.mp4"),
  "luna.mp4": require("../assets/SING_VIDEOS/luna.mp4"),
  "mama.mp4": require("../assets/SING_VIDEOS/mama.mp4"),
  "manejar.mp4": require("../assets/SING_VIDEOS/manejar.mp4"),
//   "momentito.mp4": require("../assets/SING_VIDEOS/momentito.mp4"),
  "mujer.mp4": require("../assets/SING_VIDEOS/mujer.mp4"),
  "nadar.mp4": require("../assets/SING_VIDEOS/nadar.mp4"),
  "nina.mp4": require("../assets/SING_VIDEOS/ninas.mp4"),
  "nino.mp4": require("../assets/SING_VIDEOS/ninas.mp4"),
//   "no esta.mp4": require("../assets/SING_VIDEOS/no esta.mp4"),
  "oir.mp4": require("../assets/SING_VIDEOS/or.mp4"),
  "ojala.mp4": require("../assets/SING_VIDEOS/ojala.mp4"),
  "otra vez.mp4": require("../assets/SING_VIDEOS/otra vez.mp4"),
//   "otro.mp4": require("../assets/SING_VIDEOS/otro.mp4"),
  "papa.mp4": require("../assets/SING_VIDEOS/papa.mp4"),
//   "pasos.mp4": require("../assets/SING_VIDEOS/pasos.mp4"),
  "paz.mp4": require("../assets/SING_VIDEOS/paz.mp4"),
  "pena.mp4": require("../assets/SING_VIDEOS/pena.mp4"),
  "persona.mp4": require("../assets/SING_VIDEOS/persona.mp4"),
  "querer.mp4": require("../assets/SING_VIDEOS/querer.mp4"),
  "quinto.mp4": require("../assets/SING_VIDEOS/quinto.mp4"),
  "radio.mp4": require("../assets/SING_VIDEOS/radio.mp4"),
  "rebanar.mp4": require("../assets/SING_VIDEOS/rebanar.mp4"),
  "regresar.mp4": require("../assets/SING_VIDEOS/regresar.mp4"),
//   "resumen.mp4": require("../assets/SING_VIDEOS/resumen.mp4"),
  "senor.mp4": require("../assets/SING_VIDEOS/senor.mp4"),
  "sentar.mp4": require("../assets/SING_VIDEOS/sentar.mp4"),
//   "soltar.mp4": require("../assets/SING_VIDEOS/soltar.mp4"),
  "soñar.mp4": require("../assets/SING_VIDEOS/soñar.mp4"),
  "tener.mp4": require("../assets/SING_VIDEOS/tener.mp4"),
  "tienda.mp4": require("../assets/SING_VIDEOS/tienda.mp4"),
  "tomar.mp4": require("../assets/SING_VIDEOS/tomar.mp4"),
//   "transformar.mp4": require("../assets/SING_VIDEOS/transformar.mp4"),
//   "unido.mp4": require("../assets/SING_VIDEOS/unido.mp4"),
//   "untar.mp4": require("../assets/SING_VIDEOS/untar.mp4"),
  "urgente.mp4": require("../assets/SING_VIDEOS/urgente.mp4"),
//   "usar.mp4": require("../assets/SING_VIDEOS/usar.mp4"),
  "valioso.mp4": require("../assets/SING_VIDEOS/valioso.mp4"),
  "ver.mp4": require("../assets/SING_VIDEOS/ver.mp4"),
  "viejo.mp4": require("../assets/SING_VIDEOS/viejo.mp4"),
  "volar.mp4": require("../assets/SING_VIDEOS/volar.mp4"),
//   "whisky.mp4": require("../assets/SING_VIDEOS/whisky.mp4"),
//   "xalapa.mp4": require("../assets/SING_VIDEOS/xalapa.mp4"),
//   "yucatan.mp4": require("../assets/SING_VIDEOS/yucatan.mp4"),
//   "zanahoria.mp4": require("../assets/SING_VIDEOS/zanahoria.mp4"),
//   "zapato.mp4": require("../assets/SING_VIDEOS/zapato.mp4"),
//   "zapote.mp4": require("../assets/SING_VIDEOS/zapote.mp4"),
};
